name: Reusable Build & Test

on:
  workflow_call:
    inputs:
      node_version:
        description: "Node.js version"
        required: true
        type: string
      run_tests:
        description: "Run tests"
        required: false
        default: true
        type: boolean

    outputs:
      test_result:
        description: "Result of the test step"
        value: ${{ jobs.build-test.outputs.test_result }}

jobs:
  build-test:
    runs-on: ubuntu-latest

    outputs:
      test_result: ${{ steps.test-result.outputs.result }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: npm install

      - name: Start application
        if: ${{ inputs.run_tests }}
        run: |
          npm start &
          sleep 5

      - name: Run tests
        if: ${{ inputs.run_tests }}
        id: tests
        run: sh test.sh

      - name: Set test result - Passed
        if: ${{ success() && inputs.run_tests }}
        id: test-result
        run: echo "result=passed" >> "$GITHUB_OUTPUT"

      - name: Set test result - Failed
        if: ${{ failure() && inputs.run_tests }}
        id: test-result-failed
        run: echo "result=failed" >> "$GITHUB_OUTPUT"

      
